# Generated by Django 3.0.8 on 2020-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_imgproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='', max_length=255),
        ),
    ]
