# Generated by Django 3.0.8 on 2020-09-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productfilters'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_filters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductFilters'),
        ),
    ]
