# Generated by Django 3.0.8 on 2020-09-11 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_product_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productfilters',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='product_brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brands'),
        ),
        migrations.AddField(
            model_name='productfilters',
            name='product_brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brands'),
        ),
    ]
